### ISSUE TITLE
Add cookie consent at blog entry

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_tfblog#38]
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/3.1.0/cookie-consent.js"></script>
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({"notice_banner_type":"headline","consent_type":"express","palette":"light","language":"en","website_name":"https://blog.threefold.io/","cookies_policy_url":"https://wiki.threefold.io/#/privacypolicy"});
});
</script>

<noscript>Cookie Consent by <a href="https://www.FreePrivacyPolicy.com/free-cookie-consent/" rel="nofollow noopener">FreePrivacyPolicy.com</a></noscript>

**Comment by Sacha96** [comment]
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/3.1.0/cookie-consent.js"></script>
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({"notice_banner_type":"headline","consent_type":"express","palette":"light","language":"en","website_name":"https://blog.threefold.io/","cookies_policy_url":"https://wiki.threefold.io/#/privacypolicy"});
});
</script>

<noscript>Cookie Consent by <a href="https://www.FreePrivacyPolicy.com/free-cookie-consent/" rel="nofollow noopener">FreePrivacyPolicy.com</a></noscript>

**Comment by xmonader** [comment]
Code is merged https://github.com/crystaluniverse/publishingtools/pull/204, requires a careful update on the publishingtools as it's now running wikis, websites, blog, and there're some technical issues with a recent upgrade in one of its dependencies
